version: "3.3"

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nats:
    image: "nats:2.1.7-scratch"
    expose:
      - "4222"
      - "8222"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nats.rule=Host(`nats.tspnhq.com`)"
      - "traefik.http.services.nats.loadbalancer.server.port=8222"
      - "traefik.http.routers.nats.entrypoints=web"

  redis:
    image: redis:6.0.4
    expose:
      - "6379"

  dcollect:
    build:
      context: ../dcollect
      cache_from:
        - docker.pkg.github.com/conthesis/dcollect/dcollect
    build: ../dcollect

    depends_on:
      - redis
    expose:
      - "8000"
    environment:
      - REDIS_URL=redis://redis/
      - CAS_URL=http://cas:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dcollect.rule=Host(`dcollect.tspnhq.com`)"
      - "traefik.http.services.dcollect.loadbalancer.server.port=8000"
      - "traefik.http.routers.dcollect.entrypoints=web"

  entwatcher:
    build: ../entwatcher
    depends_on:
      - dcollect
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.entwatcher.rule=Host(`entwatcher.tspnhq.com`)"
      - "traefik.http.services.entwatcher.loadbalancer.server.port=8000"
      - "traefik.http.routers.entwatcher.entrypoints=web"
    environment:
      - DCOLLECT_BASE_URL=http://dcollect:8000
      - ENTWATCHER_BASE_URL=http://entwatcher:8000
      - REDIS_URL=redis://redis/
      - CAS_URL=http://cas:8000

  compgraph:
    build: ../compgraph
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.compgraph.rule=Host(`compgraph.tspnhq.com`)"
      - "traefik.http.routers.compgraph.entrypoints=web"
      - "traefik.http.services.compgraph.loadbalancer.server.port=8000"

  cas:
    build: ../cas
    expose:
      - "8000"
    environment:
      - REDIS_URL=redis://redis/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cas.rule=Host(`cas.tspnhq.com`)"
      - "traefik.http.routers.cas.entrypoints=web"
      - "traefik.http.services.cas.loadbalancer.server.port=8000"
