version: "3.3"

services:
  traefik:
    image: "traefik:2.4"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nats:
    image: "nats:2.1.7-scratch"
    expose:
      - "4222"
      - "8222"
    ports:
      - "4222:4222"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nats.rule=Host(`nats.tspnhq.com`)"
      - "traefik.http.services.nats.loadbalancer.server.port=8222"
      - "traefik.http.routers.nats.entrypoints=web"

  redis:
    image: redis:6.0.6
    expose:
      - "6379"
    ports:
      - "6379:6379"

  dcollect:
    build:
      context: ../dcollect
      cache_from:
        - docker.pkg.github.com/conthesis/dcollect/dcollect
    build: ../dcollect
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis/
      - NATS_URL=nats://nats:4222
      - STORAGE_DRIVER=redis

  entwatcher:
    build: ../entwatcher
    environment:
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis/
      - STORAGE_DRIVER=redis

  compgraph:
    build: ../compgraph
    environment:
      - NATS_URL=nats://nats:4222

  minio:
    image: minio/minio
    expose:
      - 9000
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - minio:/data
    command: server /data

  cas:
    build: ../cas
    environment:
      - MINIO_ENDPOINT=minio:9000
      - NATS_URL=nats://nats:4222
      - STORAGE_DRIVER=minio
      - MINIO_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - MINIO_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  actions:
    build: ../actions
    environment:
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis/

  maestro:
    build: ../maestro
    environment:
      - NATS_URL=nats://nats:4222

  cfsd:
    build: ../cfsd
    environment:
      - NATS_URL=nats://nats:4222

  dgraph-importer:
    build: ../dgraph-importer
    environment:
      - NATS_URL=nats://nats:4222

  admin:
    build: ../admin
    expose:
      - "3000"
    environment:
      - NATS_URL=nats://nats:4222
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.tspnhq.com`)"
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.services.admin.loadbalancer.server.port=3000"


  dgraph:
    image: dgraph/standalone:v20.07.0
    expose:
      - "8080"
      - "9080"
      - "8000"
    ports:
      - 8081:8080
      - 9081:9080
      - 8001:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dgraph.rule=Host(`dgraph.tspnhq.com`)"
      - "traefik.http.routers.dgraph.entrypoints=web"
      - "traefik.http.services.dgraph.loadbalancer.server.port=8000"

volumes:
  minio:
